In [25]:
import numpy as np

y_pred = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

## Mean Absolute Error

*w/o numpy*

In [26]:
def mae(y_pred, y_true):
    total_error = 0
    
    for yp, yt in zip(y_pred, y_true):
        total_error += abs(yp - yt)
    
    print("Total error is:", total_error)
    
    mae = total_error / len(y_pred)
    print("Mean absolute error is:", mae)
    return mae

mae(y_pred, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

*Implementing same thing using numpy*

In [27]:
np.abs(y_pred - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [28]:
np.mean(np.abs(y_pred - y_true)) # mae

0.5

In [29]:
np.sum(np.abs(y_pred - y_true)) # total error

2.5

In [30]:
def mae_np(y_pred, y_true):
    return np.mean(np.abs(y_pred - y_true))

mae_np(y_pred, y_true)

0.5

## Mean Squared Error

*w/o numpy*

In [31]:
def mse(y_pred, y_true):
    total_error = 0
    
    for yp, yt in zip(y_pred, y_true):
        # total_error += (yp - yt) * (yp - yt)
        total_error += (yp - yt) ** 2
    
    print("Total error is:", total_error)
    
    mse = total_error / len(y_pred)
    print("Mean squared error is:", mse)
    return mse

mse(y_pred, y_true)

Total error is: 1.83
Mean squared error is: 0.366


0.366

*with numpy*

In [32]:
def mse_np(y_pred, y_true):
    return np.mean(np.square(y_pred - y_true))

mse_np(y_pred, y_true)

0.366

## Log Loss or Binary Cross Entropy

In [33]:
epsilon = 1e-15

y_pred

array([1, 1, 0, 0, 1])

In [34]:
np.log(y_pred)

C:\Users\Hp\AppData\Local\Temp\ipykernel_16728\4184140517.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_pred)


array([  0.,   0., -inf, -inf,   0.])

In [35]:
# replacing 0 with value very close to 0 -> (epsilon)
y_pred_new = [max(i, epsilon) for i in y_pred]
y_pred_new

[1, 1, 1e-15, 1e-15, 1]

In [36]:
# replacing 1 with value very close to 1 -> (1-epsilon)
y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [37]:
y_pred_new = np.array(y_pred_new)
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [38]:
- np.mean(y_true * np.log(y_pred_new) + (1 - y_true) * np.log(1 - y_pred_new))

17.2696280766844

log loss = 17.2696280766844

in a function

In [39]:
def log_loss(y_true, y_pred):
    epsilon = 1e-15
    
    y_pred_new = [max(i, epsilon) for i in y_pred]
    y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
    
    y_pred_new = np.array(y_pred_new)
    
    return - np.mean(y_true * np.log(y_pred_new) + (1 - y_true) * np.log(1 - y_pred_new))

log_loss(y_true, y_pred)

17.2696280766844